name: CI Workflow for All Pushes and Pull Requests

on:
  push:  # Trigger on any push
    branches:
      - '**'  # Match all branches
  pull_request:  # Trigger on pull requests
    branches:
      - main  # When PR targets the main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for Java projects)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the Java distribution

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: mvn install

      # Step 4: Run Tests
      - name: Run Tests
        run: mvn test

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (for linting frontend code, adjust if not needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Linter
      - name: Run Linter
        run: npm run lint
