name: CI Workflow for Push and Pull Requests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Create Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: List Files (Debugging)
      - name: List Files
        run: ls -R  # Lists files to help find Java files location

      # Step 3: Set up Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 4: Compile Java Files (Adjust path based on your directory structure)
      - name: Compile Java Files
        run: javac -d out $(find src -name "*.java")  # Update path based on your project

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ github.repository }}:latest .

      # Step 6: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push ${{ github.repository }}:latest
