name: CI Workflow for Push and Pull Requests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Compile Java Files
      - name: Compile Java Files
        run: |
          javac -d out src/**/*.java

      # Step 4: Run Tests (Update this step based on your testing setup)
      - name: Run Tests
        run: |
          java -cp out org.junit.runner.JUnitCore com.example.MyTestClass
