name: CI Workflow for All Pushes and Pull Requests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Navigate to the directory containing the pom.xml (if necessary)
      - name: Build and Test with Maven
        run: |
          cd path/to/project  # Change this to your directory containing pom.xml
          mvn install
          mvn test
