name: CI Workflow for Push and Pull Requests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: List Files (Debugging)
      - name: List Files
        run: ls -R

      # Step 3: Set up Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Using Temurin JDK

      # Step 4: Compile Java Files (Adjust path as needed)
      - name: Compile Java Files
        run: javac -d out $(find src -name "*.java")

      # Step 5: Run Tests (Replace `MainClass` with your test runner o
